// <auto-generated />
using System;
using EscolaASC_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EscolaASC_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EscolaASC_WebAPI.Model.Materia", b =>
                {
                    b.Property<int>("Materiaid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("media");

                    b.Property<string>("nome");

                    b.Property<int>("peso1");

                    b.Property<int>("peso2");

                    b.Property<int>("peso3");

                    b.Property<string>("situacao");

                    b.HasKey("Materiaid");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("EscolaASC_WebAPI.Model.Prova", b =>
                {
                    b.Property<int>("Provaid")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Materiaid");

                    b.Property<int>("prova1");

                    b.Property<int>("prova2");

                    b.Property<int>("prova3");

                    b.Property<int>("provaFinal");

                    b.HasKey("Provaid");

                    b.HasIndex("Materiaid");

                    b.ToTable("Prova");
                });

            modelBuilder.Entity("EscolaASC_WebAPI.Model.Prova", b =>
                {
                    b.HasOne("EscolaASC_WebAPI.Model.Materia", "materia")
                        .WithMany("provas")
                        .HasForeignKey("Materiaid");
                });
#pragma warning restore 612, 618
        }
    }
}
